name: bazarr
services:
  bazarr:
    container_name: bazarr
    deploy:
      resources:
        reservations:
          memory: "67108864"
        limits:
          memory: 13903M
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    image: linuxserver/bazarr:1.2.2
    ports:
      - target: 6767
        published: "6767"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Media/Movies
        target: /movies
      - type: bind
        source: /DATA/Media/TV Shows
        target: /tv
      - type: bind
        source: /DATA/AppData/bazarr/config
        target: /config
      - type: bind
        target: /DATA
        source: /DATA
